### ISSUE TITLE
```NameError: name 'genbankDict' is not defined``` when the input gbk file is not detected with domain. 

### ISSUE THREAD

**Issue by neptuneyt** [medema-group/BiG-SCAPE#103]
Dear developer, 
I update bigscape to v1.1.7， I encountered an ```NameError: name 'genbankDict' is not defined``` when the input gbk file is not detected with domain. Even through I debug with ```genbankDict = {}``` at line 1294. 
The command and log as below. The issue was only occured with any of input gbk without detection of domain.
```bash
(bigscape1.1.7) [yut@node06 TestData]$ time bigscape.py  -i bigscape_input/ -o bigscape_result
... 
Starting with 20 files
 Files that had its sequence extracted: 0

Creating output directories
 SVG folder already exists
 Networks folder already exists

Trying threading on 128 cores

Predicting domains using hmmscan
 All fasta files had already been processed
 Finished generating domtable files.

Parsing hmmscan domtable files
 Warning! The following domtable files had not been processed: MAG_1908QYC2_metabat2_bin.49~QYC2.1908_Scaff0430441.region001
  No domains where found in MAG_1908QYC2_metabat2_bin.49~QYC2.1908_Scaff0430441.region001.domtable. Removing it from further analysis
Traceback (most recent call last):
  File "/datanode02/yut/Software/BiG-SCAPE-1.1.7/bigscape.py", line 3333, in <module>
    main()
  File "/datanode02/yut/Software/BiG-SCAPE-1.1.7/bigscape.py", line 2522, in main
    parseHmmScan(domtableFile, pfd_folder, pfs_folder, options.domain_overlap_cutoff)
  File "/datanode02/yut/Software/BiG-SCAPE-1.1.7/bigscape.py", line 1294, in parseHmmScan
    info = genbankDict.get(outputbase)
NameError: name 'genbankDict' is not defined
```
* the MAG_1908QYC2_metabat2_bin.49~QYC2.1908_Scaff0430441.region001.gbk as below
```bash
(bigscape1.1.7) [yut@node06 TestData]$ cat  bigscape_input/MAG_1908QYC2_metabat2_bin.49~QYC2.1908_Scaff0430441.region001.gbk
LOCUS       QYC2.1908_Scaff0430441  1719 bp    DNA     linear   UNK 01-JAN-1980
DEFINITION  QYC2.1908_Scaff0430441.
ACCESSION   QYC2.1908_Scaff0430441
VERSION     QYC2.1908_Scaff0430441
KEYWORDS    .
SOURCE
  ORGANISM
            .
COMMENT     ##antiSMASH-Data-START##
            Version      :: 7.1.0
            Run date     :: 2023-12-05 23:53:54
            NOTE: This is a single region extracted from a larger record!
            Orig. start  :: 0
            Orig. end    :: 1719
            ##antiSMASH-Data-END##
FEATURES             Location/Qualifiers
     protocluster    1..1719
                     /aStool="rule-based-clusters"
                     /category="other"
                     /contig_edge="True"
                     /core_location="[139:1519]"
                     /cutoff="30000"
                     /detection_rule="NasY"
                     /neighbourhood="30000"
                     /product="acyl_amino_acids"
                     /protocluster_number="1"
                     /tool="antismash"
     proto_core      140..1519
                     /aStool="rule-based-clusters"
                     /tool="antismash"
                     /cutoff="30000"
                     /detection_rule="NasY"
                     /neighbourhood="30000"
                     /product="acyl_amino_acids"
                     /protocluster_number="1"
     cand_cluster    1..1719
                     /candidate_cluster_number="1"
                     /contig_edge="True"
                     /detection_rules="NasY"
                     /kind="single"
                     /product="acyl_amino_acids"
                     /protoclusters="1"
                     /tool="antismash"
     region          1..1719
                     /candidate_cluster_numbers="1"
                     /contig_edge="True"
                     /product="acyl_amino_acids"
                     /region_number="1"
                     /rules="NasY"
                     /tool="antismash"
     CDS             140..1519
                     /gene_functions="biosynthetic (rule-based-clusters)
                     acyl_amino_acids: NasY"
                     /gene_kind="biosynthetic"
                     /locus_tag="ctg514_1"
                     /sec_met_domain="NasY (E-value: 4.9e-17, bitscore: 48.0,
                     seeds: 100, tool: rule-based-clusters)"
                     /transl_table=11
                     /translation="MKKLRLSLLRRLLRRWSRSLLAALPESVRFAFYRRMADLKPVSSG
                     RLELKIAHTQEELTACFGLLHDAYVSSGFMRPHPSGLRVTPYHALPTTTTLCAKVDGVV
                     VGTISIIREGVFGFPMQSAFDISGVRAKDGRIAEISALAIHPRWRKTGGSILFPLMKFM
                     YGYCTRYFDTRHLVIAVNPAHIEMYESLLFFRRLTANVVEHYDFVNGAPAVGATLDLHE
                     APELFKRAYEHKPGRRNLHRYFTETELPEITYPPRPWHTSNDPMLTPELLDHFFHEHTA
                     FNDLDDRRQSLLHSIYREPEWARVLPKLAPAAAAGVNLRRETRYSMSCPATLVASDQPA
                     NAQRVTIVEISEHGFLARTSRALPDGTQWSLVAELAEGVFSRGQVKLVRQARSDSGQSY
                     GFHIENPDDAWRRCVAWLDEAEQLPTSADIDADPAAPTALRTAAMSGSRELLSRRAHEC
                     V"
ORIGIN
        1 caagccgagg tcgctcagct catgagcagc ctgtaactct ttctttcaag tccagggttg
       61 cccgcggtca agcctaagct gccgcagtcg aaatcaagga cgagggcgga cagcccccgc
      121 accaaagagc cggcaaccca tgaagaaatt gaggctttcc ttgctgcggc gattgcttcg
      181 ccgctggtcc aggtcgctgc tggctgcttt gcccgagtcc gtacgatttg ctttctaccg
      241 gcgcatggcg gacctcaagc ccgtcagcag cggtcggctg gaactgaaga ttgcgcacac
      301 tcaggaagag ctgacggcct gcttcggcct gcttcatgac gcttacgtga gcagcggctt
      361 catgcgtccc catccctcag gcctgcgggt gacgccgtac cacgctttgc cgacgaccac
      421 gacactttgt gccaaggtcg atggcgtggt ggtcggcacg atctcgatca tccgcgaagg
      481 cgttttcgga ttcccgatgc agtcagcctt cgacatctca ggcgtgcgtg ccaaggacgg
      541 ccgcattgcc gagatatctg cactggccat ccacccgcgc tggcgcaaga cgggcgggtc
      601 gatcctgttc ccattgatga agttcatgta cgggtactgc acgcgatatt tcgacacccg
      661 ccatctggtg atcgccgtga accccgcgca catcgagatg tacgagtcgt tgctattttt
      721 ccgccgcttg acagccaacg tggtggaaca ctacgacttc gtcaacggcg cacctgctgt
      781 gggcgcgacg ctggacctcc acgaggcgcc tgaactcttc aaacgcgcct atgaacacaa
      841 gccaggccgg cgaaatctgc accgttattt cacagagaca gagttgccgg aaatcaccta
      901 cccgcccagg ccctggcaca ccagcaacga cccgatgttg acgccagagt tgctggatca
      961 cttcttccac gaacacacgg cgttcaacga cctcgatgac cggcgccaaa gcctgctgca
     1021 ctccatctac cgtgagcccg agtgggccag agtgctgccc aaactggcgc cggctgcagc
     1081 cgccggcgtc aacttgagac gcgaaacgcg ctattcgatg agttgccctg ccacgctggt
     1141 ggcctcggat cagcccgcga atgcgcagcg ggtcaccatc gtcgaaatct ccgaacatgg
     1201 ctttctggcc agaacgtccc gtgcgctgcc tgacggcacc caatggagcc tggtggccga
     1261 actcgccgag ggcgtgttca gccgcggcca ggtcaagctc gtgcggcagg ccagaagcga
     1321 cagcggacag agctacggtt tccatatcga gaaccccgac gacgcctggc gacgctgcgt
     1381 cgcttggttg gatgaggcgg aacaattgcc gaccagcgct gatatcgacg cagatccagc
     1441 cgcgccgact gcgctgcgaa ccgcggcaat gtcaggaagt cgcgagctat tgtcccggcg
     1501 ggcacacgag tgcgtttgat tggcaccgcc cctctgccac gggctgagga accctggccg
     1561 tgccgattga tcgaattgtt gcggtccaga actgagtgca ggccttgacc gccgaagcgc
     1621 cgggccgtcg atatgccttt tcccgcaccg cagcgcgaga ccgacaacgt cgggacgatc
     1681 tcccgacaac cggtctggca aggttttgaa tgttgtgtc
//

```
I am looking forward you reply.

**Comment by cfz1998** [comment]
> Hello!
> 
> Thank you for your bug report. This is an issue with an update we pushed recently.
> 
> Please try version 1.1.5 while we try to resolve these issues.

Hi! @adraismawur.
I got the same error. The version is `BiG-SCAPE 1.1.5 (2022-11-14)`.

**Comment by cfz1998** [comment]
Hi~ @adraismawur
I just changed some lines in lines 1294-1299.
Does this have other problems?
![image](https://github.com/medema-group/BiG-SCAPE/assets/60096719/950b0aa6-ac6e-4972-987f-dedbb4b634ed)



Thank you for your reply!

**Comment by lytze** [comment]
I had the save problem with v1.1.7. I fixed this bug with adding

```python3
global genbankDict
```

before line `2290`

```python3
    global bgc_info
    bgc_info = {}
    global genbankDict  ## add this line
    genbankDict = {}
```

**Comment by adraismawur** [comment]
**For future users looking at this issue: see bottom of this post.**



> Hi~ @adraismawur I just changed some lines in lines 1294-1299. Does this have other problems? ![image](https://private-user-images.githubusercontent.com/60096719/292798729-950b0aa6-ac6e-4972-987f-dedbb4b634ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MDQ3NTEsIm5iZiI6MTcwNDcwNDQ1MSwicGF0aCI6Ii82MDA5NjcxOS8yOTI3OTg3MjktOTUwYjBhYTYtYWM2ZS00OTcyLTk4N2YtZGVkYmI0YjYzNGVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDA5MDA1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiNzUxZjQ4NWE4YzhlNjYyZjA0NDg1MDA2YmFmYTZhM2U1MTgwOWI0ZmE3Zjk3ZGQ0MTA3ZmRmMmVmZGZhYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yc0CGCfabEp8OPaC7UVWonHxmOrnjdD-ahyZHUlwLLU)
> 
> Thank you for your reply!

I am 90% sure that should be fine. If it works, it works ;)

> I had the save problem with v1.1.7. I fixed this bug with adding
> 
> ```python
> global genbankDict
> ```
> 
> before line `2290`
> 
> ```python
>     global bgc_info
>     bgc_info = {}
>     global genbankDict  ## add this line
>     genbankDict = {}
> ```

Out of interest, are you running BiG-SCAPE as a python file using `python bigscape.py` or as a module using `python -m bigscape` or similar?


For future users looking at this issue:

We are working on version 2 of BiG-SCAPE which will be properly installable using Bioconda.

The issues with a Bioconda installation are that they are ran as modules, which does not play nice with the global variables that were used in 1.x. Thoroughly assessing and fixing the various globals that are present in 1.x is not something we want to do at this moment so we discourage installing BiG-SCAPE through Bioconda and running it as a module.

The package still exists on Bioconda because there is no way to remove package versions, unfortunately. Sorry for the inconvenience this causes and we hope to release version 2 soon.
