### ISSUE TITLE
dataclasses module not installed for python=3.6

### ISSUE THREAD

**Issue by snail123815** [medema-group/BiG-SCAPE#12]
Hi,

I am installing BiG-SCAPE from `releases` tarball. Version 1.1.4.

The created conda environment using `environment.yml` itself does miss a dependency: `dataclasses`.

I got an error when running `bigscape.py`:

```
Traceback (most recent call last):
  File "appBuilds/BiG-SCAPE-1.1.4/bigscape.py", line 75, in <module>
    import networkx as nx
  File "/opt/anaconda3/envs/bigscape/lib/python3.6/site-packages/networkx/__init__.py", line 81, in <module>
    from networkx import algorithms
  File "/opt/anaconda3/envs/bigscape/lib/python3.6/site-packages/networkx/algorithms/__init__.py", line 81, in <module>
    from networkx.algorithms import tree
  File "/opt/anaconda3/envs/bigscape/lib/python3.6/site-packages/networkx/algorithms/tree/__init__.py", line 1, in <module>
    from .branchings import *
  File "/opt/anaconda3/envs/bigscape/lib/python3.6/site-packages/networkx/algorithms/tree/branchings.py", line 30, in <module>
    from dataclasses import dataclass, field
ModuleNotFoundError: No module named 'dataclasses'
```

The `dataclasses` module is [built-in only from python3.7](https://pypi.org/project/dataclasses/). My `networkx` version (as installed by conda using `environment.yml` on 20220623) is 2.7.1.

This problem is caused by conda during solving dependencies for `networkx`.

Possible solutions here are:

- Use a fixed lower version of `networkx`.
- Include `dataclasses` in `environment.yml`
- Bump python version to 3.7.

**Comment by jorgecnavarrom** [comment]
Fixed in the last commits (ed7364e86fbb72772ee48f9035bcdbc101dddff7 and bcc58de833ab0dc7fabe3608f018da05874f0d42)
I only included dataclasses and will bump the Python version along with scikit-learn's in a following release
