### ISSUE TITLE
"Did not find file MIBiG_3.1_final.zip. Please re-download it from the official repository"

### ISSUE THREAD

**Issue by dfl5440** [medema-group/BiG-SCAPE#172]
Hi Everyone, the title is the error I am getting, I installed big scape using the github wiki's instillation guide, I used miniconda to do so. I also tried downloading MIBIG_3.1_final.zip from the github and placing it in the bigscape directory however that did not work as well.

Thank you

**Comment by jorgecnavarrom** [comment]
Hi
It's a strange error, as everything should've been copied. The zip file should go into the `Annotated_MIBiG_reference` subfolder inside the BiG-SCAPE folder

**Comment by dfl5440** [comment]
Hi, I just wanted to follow up, I saw that others ran into this issue, I believe the issue occurs when someone installs the archive v1.1.5.zip version when following the instillation instructions. 

When I installed a more up to date version it worked, I have the mibig data base however when I go to run BiG-SCAPE with the --mibig flag I run into an issue when BiG-SCAPE attempts to generate the html:

```
 Using hmmalign
launch_hmmalign took 102.490 seconds
 Trying to read domain alignments (*.algn files)
Traceback (most recent call last):
  File "BiG-SCAPE-1.1.8/bigscape.py", line 3333, in <module>
    main()
  File "BiG-SCAPE-1.1.8/bigscape.py", line 2828, in main
    shutil.copy(os.path.join(os.path.dirname(os.path.realpath(__file__)), "html_template", "overview_html"), os.path.join(network_html_folder_cutoff, "overview.html"))
  File "/storage/home/dfl5440/miniconda3/envs/bigscape/lib/python3.6/shutil.py", line 245, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/storage/home/dfl5440/miniconda3/envs/bigscape/lib/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/scratch/dfl5440/BiG-SCAPE-1.1.8/html_template/overview_html'
```

also I recieve this error earlier

```
 Trying to read bundled MIBiG BGCs as reference

Importing MIBiG files
   Error with file /scratch/dfl5440/BiG-SCAPE-1.1.8/Annotated_MIBiG_reference/MIBiG_3.1_final/BGC0001852.gbk:
    ''ascii' codec can't decode byte 0xce in position 63: ordinal not in range(128)'
    (This file will be excluded from the analysis)
   Error with file /scratch/dfl5440/BiG-SCAPE-1.1.8/Annotated_MIBiG_reference/MIBiG_3.1_final/BGC0002139.gbk:
    ''ascii' codec can't decode byte 0xce in position 4086: ordinal not in range(128)'
    (This file will be excluded from the analysis)
   Error with file /scratch/dfl5440/BiG-SCAPE-1.1.8/Annotated_MIBiG_reference/MIBiG_3.1_final/BGC0001149.gbk:
    ''ascii' codec can't decode byte 0xe2 in position 5332: ordinal not in range(128)'
    (This file will be excluded from the analysis)
   Error with file /scratch/dfl5440/BiG-SCAPE-1.1.8/Annotated_MIBiG_reference/MIBiG_3.1_final/BGC0001231.gbk:
    ''ascii' codec can't decode byte 0xce in position 6326: ordinal not in range(128)'
    (This file will be excluded from the analysis)
   Error with file /scratch/dfl5440/BiG-SCAPE-1.1.8/Annotated_MIBiG_reference/MIBiG_3.1_final/BGC0001851.gbk:
    ''ascii' codec can't decode byte 0xce in position 7722: ordinal not in range(128)'
    (This file will be excluded from the analysis)
   Error with file /scratch/dfl5440/BiG-SCAPE-1.1.8/Annotated_MIBiG_reference/MIBiG_3.1_final/BGC0000199.gbk:
    ''ascii' codec can't decode byte 0xce in position 5142: ordinal not in range(128)'
    (This file will be excluded from the analysis)
  Warning: Input set has files with no Biosynthetic Genes (affects alignment mode)
   See no_biosynthetic_genes_list.txt
   ```
