### ISSUE TITLE
Cant run BiG-Scape after installation

### ISSUE THREAD

**Issue by Dmente92** [medema-group/BiG-SCAPE#180]
Dear all,

I have installed BiG-Scape following the wiki. Sadly, when I execute the command 'python bigscape.py --version', I just get the following error:

Traceback (most recent call last):
  File "bigscape.py", line 63, in <module>
    from sklearn.cluster import AffinityPropagation
  File "/home/yami/miniconda3/envs/bigscape/lib/python3.6/site-packages/sklearn/cluster/__init__.py", line 6, in <module>
    from .spectral import spectral_clustering, SpectralClustering
  File "/home/yami/miniconda3/envs/bigscape/lib/python3.6/site-packages/sklearn/cluster/spectral.py", line 15, in <module>
    from ..metrics.pairwise import pairwise_kernels
  File "/home/yami/miniconda3/envs/bigscape/lib/python3.6/site-packages/sklearn/metrics/__init__.py", line 33, in <module>
    from . import cluster
  File "/home/yami/miniconda3/envs/bigscape/lib/python3.6/site-packages/sklearn/metrics/cluster/__init__.py", line 20, in <module>
    from .unsupervised import silhouette_samples
  File "/home/yami/miniconda3/envs/bigscape/lib/python3.6/site-packages/sklearn/metrics/cluster/unsupervised.py", line 12, in <module>
    from ..pairwise import pairwise_distances
  File "/home/yami/miniconda3/envs/bigscape/lib/python3.6/site-packages/sklearn/metrics/pairwise.py", line 30, in <module>
    from .pairwise_fast import _chi2_kernel_fast, _sparse_manhattan
ImportError: libgfortran.so.3: cannot open shared object file: No such file or directory

Any idea how to solve this issue. Thanks

Regards, Daniel

**Comment by jorgecnavarrom** [comment]
Hi Daniel

What's your version of scikit-learn? Versions higher than 0.19.2 have created problems in the past

**Comment by Dmente92** [comment]
Hi @jorgecnavarrom , my version of scikit-learn is precisely 0.19.2

**Comment by Dmente92** [comment]
Hi @jorgecnavarrom , I managed to solve the issue. I just uninstalled scikit-learn 0.19.2 from the conda environment and installed the v0.19.1. Everything is running fine for now. Thanks

**Comment by adriangeerre** [comment]
Hi

I followed the conda installation instruction from the wiki but I faced the same issue. I tried reinstalling with scikit-learn 0.19.1 but did not solved the issue.

I have apparently solved the issue (I still needs to test) by installing libgfortran 3.0.0 as described here: https://github.com/ContinuumIO/anaconda-issues/issues/686#issuecomment-215977843

Best
