### ISSUE TITLE
MIBIG 4.0 compatibility problem

### ISSUE THREAD

**Issue by rubenluz** [medema-group/BiG-SCAPE#229]
After having the same error as #227 with `2.0.0-beta.1` and cannot download the v4.0 of MIBIG, if done manually (downloading directly and changing the folder name to match the 3.1 automatic download) another error occurs. It seems its only compatibility problems, the antismash header version value in MIBIG 4.0 is changed to false

### error 1:
`2024-12-15 20:24:06,599 INFO    Downloading MIBiG version 4.0
Traceback (most recent call last):
  File "/home/ruben/BiG-SCAPE/bigscape.py", line 37, in <module>
    __main__.main()
  File "/home/ruben/BiG-SCAPE/big_scape/__main__.py", line 51, in main
    cli()
  File "/home/ruben/micromamba/envs/bigscape/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ruben/micromamba/envs/bigscape/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/ruben/micromamba/envs/bigscape/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ruben/micromamba/envs/bigscape/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ruben/micromamba/envs/bigscape/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ruben/micromamba/envs/bigscape/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ruben/BiG-SCAPE/big_scape/cli/cluster_cli.py", line 159, in cluster
    run_bigscape(ctx.obj)
  File "/home/ruben/BiG-SCAPE/big_scape/run_bigscape.py", line 116, in run_bigscape
    mibig_version_dir = bs_files.get_mibig(run["mibig_version"], bigscape_dir)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ruben/BiG-SCAPE/big_scape/file_input/load_files.py", line 61, in get_mibig
    download_dataset(mibig_url, mibig_dir, mibig_dir_compressed)
  File "/home/ruben/BiG-SCAPE/big_scape/file_input/load_files.py", line 87, in download_dataset
    raise ValueError("Could not download MIBiG file")
ValueError: Could not download MIBiG file
`
### error 2
`2024-12-15 20:22:25,008 ERROR   /home/ruben/BiG-SCAPE/big_scape/MIBiG/mibig_antismash_4.0_gbk/BGC0001987.gbk: Invalid antiSMASH version in GBK header
Exception in thread Thread-6 (_handle_results):
Traceback (most recent call last):
  File "/home/ruben/micromamba/envs/bigscape/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
2024-12-15 20:22:25,009 ERROR   /home/ruben/BiG-SCAPE/big_scape/MIBiG/mibig_antismash_4.0_gbk/BGC0003006.gbk: Invalid antiSMASH version in GBK header
2024-12-15 20:22:25,009 ERROR   /home/ruben/BiG-SCAPE/big_scape/MIBiG/mibig_antismash_4.0_gbk/BGC0002348.gbk: Invalid antiSMASH version in GBK header
2024-12-15 20:22:25,009 ERROR   /home/ruben/BiG-SCAPE/big_scape/MIBiG/mibig_antismash_4.0_gbk/BGC0000803.gbk: Invalid antiSMASH version in GBK header
2024-12-15 20:22:25,009 ERROR   /home/ruben/BiG-SCAPE/big_scape/MIBiG/mibig_antismash_4.0_gbk/BGC0001286.gbk: Invalid antiSMASH version in GBK header
2024-12-15 20:22:25,010 ERROR   /home/ruben/BiG-SCAPE/big_scape/MIBiG/mibig_antismash_4.0_gbk/BGC0001278.gbk: Invalid antiSMASH version in GBK header
    self.run()
  File "/home/ruben/micromamba/envs/bigscape/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ruben/micromamba/envs/bigscape/lib/python3.11/multiprocessing/pool.py", line 579, in _handle_results
2024-12-15 20:22:25,011 ERROR   /home/ruben/BiG-SCAPE/big_scape/MIBiG/mibig_antismash_4.0_gbk/BGC0001521.gbk: Invalid antiSMASH version in GBK header
2024-12-15 20:22:25,011 ERROR   /home/ruben/BiG-SCAPE/big_scape/MIBiG/mibig_antismash_4.0_gbk/BGC0001240.gbk: Invalid antiSMASH version in GBK header
2024-12-15 20:22:25,012 ERROR   /home/ruben/BiG-SCAPE/big_scape/MIBiG/mibig_antismash_4.0_gbk/BGC0000327.gbk: Invalid antiSMASH version in GBK header
2024-12-15 20:22:25,013 ERROR   /home/ruben/BiG-SCAPE/big_scape/MIBiG/mibig_antismash_4.0_gbk/BGC0001260.gbk: Invalid antiSMASH version in GBK header
2024-12-15 20:22:25,014 ERROR   /home/ruben/BiG-SCAPE/big_scape/MIBiG/mibig_antismash_4.0_gbk/BGC0000810.gbk: Invalid antiSMASH version in GBK header
2024-12-15 20:22:25,014 ERROR   /home/ruben/BiG-SCAPE/big_scape/MIBiG/mibig_antismash_4.0_gbk/BGC0000134.gbk: Invalid antiSMASH version in GBK header
2024-12-15 20:22:25,014 ERROR   /home/ruben/BiG-SCAPE/big_scape/MIBiG/mibig_antismash_4.0_gbk/BGC0003077.gbk: Invalid antiSMASH version in GBK header
2024-12-15 20:22:25,014 ERROR   /home/ruben/BiG-SCAPE/big_scape/MIBiG/mibig_antismash_4.0_gbk/BGC0001724.gbk: Invalid antiSMASH version in GBK header
2024-12-15 20:22:25,014 ERROR   /home/ruben/BiG-SCAPE/big_scape/MIBiG/mibig_antismash_4.0_gbk/BGC0002545.gbk: Invalid antiSMASH version in GBK header
2024-12-15 20:22:25,015 ERROR   /home/ruben/BiG-SCAPE/big_scape/MIBiG/mibig_antismash_4.0_gbk/BGC0000432.gbk: Invalid antiSMASH version in GBK header
2024-12-15 20:22:25,015 ERROR   /home/ruben/BiG-SCAPE/big_scape/MIBiG/mibig_antismash_4.0_gbk/BGC0002360.gbk: Invalid antiSMASH version in GBK header
2024-12-15 20:22:25,016 ERROR   /home/ruben/BiG-SCAPE/big_scape/MIBiG/mibig_antismash_4.0_gbk/BGC0001093.gbk: Invalid antiSMASH version in GBK header
2024-12-15 20:22:25,016 ERROR   /home/ruben/BiG-SCAPE/big_scape/MIBiG/mibig_antismash_4.0_gbk/BGC0001634.gbk: Invalid antiSMASH version in GBK header
2024-12-15 20:22:25,016 ERROR   /home/ruben/BiG-SCAPE/big_scape/MIBiG/mibig_antismash_4.0_gbk/BGC0000905.gbk: Invalid antiSMASH version in GBK header
2024-12-15 20:22:25,016 ERROR   /home/ruben/BiG-SCAPE/big_scape/MIBiG/mibig_antismash_4.0_gbk/BGC0001026.gbk: Invalid antiSMASH version in GBK header
2024-12-15 20:22:25,017 ERROR   /home/ruben/BiG-SCAPE/big_scape/MIBiG/mibig_antismash_4.0_gbk/BGC0000257.gbk: Invalid antiSMASH version in GBK header
2024-12-15 20:22:25,017 ERROR   /home/ruben/BiG-SCAPE/big_scape/MIBiG/mibig_antismash_4.0_gbk/BGC0001451.gbk: Invalid antiSMASH version in GBK header
2024-12-15 20:22:25,017 ERROR   /home/ruben/BiG-SCAPE/big_scape/MIBiG/mibig_antismash_4.0_gbk/BGC0000528.gbk: Invalid antiSMASH version in GBK header
2024-12-15 20:22:25,018 ERROR   /home/ruben/BiG-SCAPE/big_scape/MIBiG/mibig_antismash_4.0_gbk/BGC0002499.gbk: Invalid antiSMASH version in GBK header
    task = get()
           ^^^^^
  File "/home/ruben/micromamba/envs/bigscape/lib/python3.11/multiprocessing/connection.py", line 251, in recv
    return _ForkingPickler.loads(buf.getbuffer())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: InvalidGBKError.__init__() takes 1 positional argument but 2 were given
2024-12-15 20:22:25,018 ERROR   /home/ruben/BiG-SCAPE/big_scape/MIBiG/mibig_antismash_4.0_gbk/BGC0002692.gbk: Invalid antiSMASH version in GBK header
`

**Comment by CatarinaCarolina** [comment]
Hi Ruben,

thanks for submitting this issue! BiG-SCAPE uses an antiSMASH processed version of the MIBiG genbank files. The pre-processed version of MIBiG 4.0 made available by the antiSMASH/MIBiG team is not available yet, hence why the download does not work for 4.0 instead of 3.1. To use that version, for now, you must process it with antiSMASH first (I expect second error is happening by giving BiG-SCAPE non antismash processed MIBiG files). I’d also recommend reading the MIBiG & References section of the wiki for more detail!
